// <auto-generated />
using System;
using AuthenticationSample.BackEnd.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AuthenticationSample.BackEnd.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211027030625_logintypetoenum")]
    partial class logintypetoenum
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AuthenticationSample.BackEnd.Web.Entities.OwnerLogin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailOrMobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<int>("LoginType")
                        .HasColumnType("int");

                    b.Property<string>("OwnerMasterID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("OwnerMasterID");

                    b.ToTable("OwnerLogin");
                });

            modelBuilder.Entity("AuthenticationSample.BackEnd.Web.Entities.OwnerMaster", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("OwnerMaster");
                });

            modelBuilder.Entity("AuthenticationSample.BackEnd.Web.Entities.OwnerLogin", b =>
                {
                    b.HasOne("AuthenticationSample.BackEnd.Web.Entities.OwnerMaster", "OwnerMaster")
                        .WithMany("OwnerLogins")
                        .HasForeignKey("OwnerMasterID");

                    b.Navigation("OwnerMaster");
                });

            modelBuilder.Entity("AuthenticationSample.BackEnd.Web.Entities.OwnerMaster", b =>
                {
                    b.Navigation("OwnerLogins");
                });
#pragma warning restore 612, 618
        }
    }
}
